### ISSUE TITLE
KeyError: 'transportable' at from Mission.load_file()

### ISSUE THREAD

**Issue by iantron** [pydcs/dcs#216] opened 2022-04-05 19:42 UTC
This miz file is an export from DCS:Liberation. I believe it is a direct export, but I am not the one who created it. Let me know if there is anything else I can do to help.

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-93c9976a6d0e> in <module>
      1 m = dcs.Mission()
----> 2 m.load_file('VPAC_Campaign_part_10.miz')

/opt/conda/lib/python3.8/site-packages/dcs/mission.py in load_file(self, filename, bypass_triggers)
    373             if col_name in imp_mission["coalition"]:
    374                 self.coalition[col_name] = Coalition(col_name, imp_mission["coalition"][col_name]["bullseye"])
--> 375                 self.coalition[col_name].load_from_dict(self, imp_mission["coalition"][col_name])
    376 
    377         return True

/opt/conda/lib/python3.8/site-packages/dcs/coalition.py in load_from_dict(self, mission, d)
     82                             name=mission.translation.get_string(imp_unit["name"]),
     83                             _type=imp_unit["type"])
---> 84                         unit.load_from_dict(imp_unit)
     85 
     86                         mission.current_unit_id = max(mission.current_unit_id, unit.id)

/opt/conda/lib/python3.8/site-packages/dcs/unit.py in load_from_dict(self, d)
     75         super(Vehicle, self).load_from_dict(d)
     76         self.player_can_drive = d["playerCanDrive"]
---> 77         self.transportable = d["transportable"]
     78 
     79     def dict(self):

KeyError: 'transportable'
```

**Comment by DanAlbert** [comment] 2022-04-05 23:26
Duplicate of #214

**Closed by DanAlbert** 2022-04-05 23:26 UTC
